version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  db:
    restart: always
    image: postgres:12
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd

  app:
    restart: always
    image: getfider/fider:stable
    environment:
      VIRTUAL_HOST: feedback.yoursite.com
      LETSENCRYPT_HOST: feedback.yoursite.com
      LETSENCRYPT_EMAIL: your-email@example.com
      BASE_URL: https://feedback.yoursite.com
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable
      JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE
      EMAIL_NOREPLY: noreply@yourdomain.com
      # Email service configuration
    depends_on:
      - db
      - nginx-proxy

volumes:
  certs:
  html:
  vhostd:
